### ISSUE TITLE
BUG: 工作流编译报错 Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by pmkol** [MatsuriDayo/nekoray#1137]
## 描述问题
Error: Process completed with exit code 1.

最近两周才出现失效的，原因是
```
      - name: Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: NekoRay-${{ github.sha }}-${{ matrix.platform }}-${{ matrix.arch }}-Qt${{ matrix.qt_version }}
          path: artifacts.tgz
```
上述方式上传的artifacts.tgz
在Pack & Publish Release流程中，使用
```
      - name: Checking out sources
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
```
的方式无法下载artifacts.tgz，导致 find . -name artifacts.tgz | xargs -n1 tar xvzf 命令无效终止了流程，需要修复
